spring:
  data:
    solr:
      host: http://192.168.182.140:8080/solr
  datasource:
    url: jdbc:mysql://localhost:3306/shopdubbo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:


dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 192.168.182.140:2181
  protocol:
    port: 28811
server:
  port: 8082