dubbo:
  application:
    name: sso
  registry:
    protocol: zookeeper
    address: 192.168.182.140:2181
server:
  port: 9095
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.182.140
    port: 5672
    username: guest
    password: guest
    virtual-host: /
