dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.182.140:2181
  protocol:
    port: 28805
server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopdubbo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  redis:
    host: 192.168.182.140
    port: 6379
    password: java123
    timeout: 10000