dubbo:
  application:
    name: index
  registry:
    protocol: zookeeper
    address: 192.168.182.140:2181
server:
  port: 9091
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/shopdubbo?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:


