dubbo:
  application:
    name: sms-service
  registry:
    protocol: zookeeper
    address: 192.168.182.140:2181
  protocol:
    port: 28815
server:
  port: 8083
spring:
  rabbitmq:
    host: 192.168.182.140
    port: 5672
    username: guest
    password: guest
    virtual-host: /
